#!/bin/ruby
require 'autotest/fsevent'


module Autotest::Growl
  def self.growl title, msg, img, pri=0, stick="" 
    system "growlnotify -n autotest --image #{img} -p #{pri} -m #{ msg.inspect} #{title} #{stick}" 
  end

  Autotest.add_hook :ran_command do |at|
    image_root = "~/.autotest_images"
    results = [at.results].flatten.join("\n")
    results.gsub!(/\\e\[\d+m/,'')
    output = results.slice(/(\d+)\sexamples?,\s(\d+)\sfailures?(,\s(\d+)\spending?|)/)
    full_sentence, green, failures, garbage, pending = $~.to_a.map(&:to_i)
    if output
      if failures > 0
        growl "FAIL", "#{output}", "#{image_root}/fail.png"
      elsif pending > 0
        growl "Pending", "#{output}", "#{image_root}/pending.png"
      else
        growl "Pass", "#{output}", "#{image_root}/pass.png"
      end
    end
  end
end
