prepend() { [ -d "$2" ] && eval $1=\"$2\$\{$1:+':'\$$1\}\" && export $1 ; }

# general
export EDITOR='vim'
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-8"

export TERM=xterm-256color
[ -n "$TMUX" ] && export TERM=screen-256color

#homebrew
export HOMEBREW_EDITOR=vim

# go
export GOPATH=$HOME/Documents/code/go
export GOBIN=$GOPATH/bin

export PATH=$PATH:$GOPATH

prepend PATH /usr/local/bin
