ZSH=$HOME/.oh-my-zsh
ZSH_HISTORY_PATH=$HOME/.zsh_history
ZSH_CUSTOM=$HOME/.zsh_profile.d
ZSH_THEME="miloshadzic"

DISABLE_AUTO_UPDATE=true

plugins=(vi-mode colored-man vagrant history-substring-search)

unset MAILCHECK
unsetopt auto_name_dirs
unsetopt nomatch

setopt nullglob

alias rspec="noglob rspec"

source $ZSH/oh-my-zsh.sh
source $HOME/.aliasrc

prepend PATH /usr/local/share/npm/lib/node_modules
prepend PATH /usr/local/share/npm/bin
prepend PATH /usr/local/bin
