ZSH=$HOME/.oh-my-zsh
ZSH_HISTORY_PATH=$HOME/.zsh_history

unset MAILCHECK
unsetopt auto_name_dirs

setopt nullglob

ZSH_THEME="miloshadzic"

plugins=(osx brew vi-mode rake)

source $ZSH/oh-my-zsh.sh

for zsh_source in $HOME/.zsh_profile.d/*.zsh; do
  source $zsh_source
done

source $HOME/.aliasrc

export PATH=/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin
export PATH=$PATH:$HOME/.rvm/bin
